- name: Configuration and deployment
  gather_facts: true
  hosts: tag_Name_Docker
  become: yes
  tasks:
    - name: Install apt dependencies
      apt:
          pkg:
          - python-pip
          update_cache: yes
    - name: Install python dependencies
      pip:
          name: docker
    - name: Run container
      docker_container:
          name: nginx
          image: nginx
          ports:
          - '80:80'
